### ISSUE TITLE
Idea - Explosions

### ISSUE THREAD

**Issue by Cetty** [Joecorleone/Derailer#2]
Crash player when to touch each other

**Comment by Joecorleone** [comment]
How do you want to do this? 

1. If two players are on the same tile at the same tile. 
2. If they are on the same point on a tile and the same path
3. If they are on the same point on a tile independent of the path
4. If they touch each other

Option 1: Might be unexpected
Option 2: Probably the easiest to implement, but in this case, they crash anyway. Has an impact when the victory condition is "distance"
Option 3: Slightly better then Option 2, but it might be not obvious to the player
Option 4: Well, this sounds difficult and currently the assets for all carts have the same size. We would have to create a collision polygon and check for collision after each move ... Then the selection of the theme would even have an impact on gameplay, which would be a bonus to me.
What is your opinion?

**Comment by Cetty** [comment]
Currently implemented option 3. Option 4 would be interesting to test.

**Comment by Joecorleone** [comment]
Great, let's leave it at Option 3 for now. 
How about implementing a GameOption "Collision On/Off"?

**Comment by Joecorleone** [comment]
Okay, a simple animation and the GameOption is implemented. Let's keep this issue open until the collision polygon is implemented.

**Comment by Joecorleone** [comment]
Replaced collision detection from distance to rectangular Polygon. can be extended to an arbitrary Polygon if a theme so requires.
